In [23]:
import os
import yaml

In [2]:
import numpy as np

In [2]:
from pprint import pprint

In [3]:
from config.config_utils import dict_recursive_update
from config.config import cfg

from easydict import EasyDict as edict

In [18]:
from data.pascalvoc.pascalvoc import PascalVOC

Using TensorFlow backend.


In [26]:
from model.networks.baseline import Baseline

In [31]:
from model.callbacks.metric_callbacks import MAPCallback
from model.callbacks.save_callback import SaveModel
from model.callbacks.scheduler import lr_scheduler
from model.callbacks.relabeling_callback import RelabelCallback

## debug config

In [4]:
config_path = '/home/caleml/partial-labels/config/pv_baseline50_sgd_448lrs.yaml'
with open(config_path, 'r') as f_in:
    options = yaml.safe_load(f_in)

In [5]:
options

{'archi': {'classifier': 'resnet50', 'loss': 'bce', 'name': 'baseline'},
 'batch_size': 16,
 'callbacks': {'lr_factor': 0.1, 'lr_trigger': [10]},
 'dataset': {'name': 'pascalvoc',
  'path': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
  'test': 'test',
  'train': 'trainval'},
 'image': {'img_size': 448},
 'training': {'n_epochs': 20, 'optimizer': 'sgd', 'start_lr': 0.01}}

In [6]:
pprint(cfg)
old_cfg = cfg

{'BATCH_SIZE': 32,
 'CALLBACK': {'LR_FACTOR': 0.1,
              'LR_TRIGGER': [],
              'MIN_DELTA': 0.0,
              'PATIENCE': 10,
              'PATIENCE_LR': 2,
              'TENSORBOARD': {'SAVE_GRAPH': True, 'USE_TENSORBOARD': False}},
 'DATAAUGMENTATION': {'DEFAULT_DICT': {'horizontal_flip': True}},
 'DATASET': {'SHUFFLE': True},
 'DEBUG': {'IS_TEST': False},
 'EPSILON': 1e-07,
 'IMAGE': {'IMG_SIZE': 448, 'N_CHANNELS': 3},
 'MULTIP': {'MAX_QUEUE_SIZE': 10, 'N_WORKERS': 2, 'USE_MULTIPROCESS': False},
 'RANDOM_SEED': 1,
 'TRAINING': {'OPTIMIZER': 'adam', 'START_LR': 0.0001},
 'VERBOSE': True}


In [7]:
new_config = edict(options)
dict_recursive_update(cfg, new_config)

{'ARCHI': {'CLASSIFIER': 'resnet50', 'LOSS': 'bce', 'NAME': 'baseline'},
 'BATCH_SIZE': 16,
 'CALLBACK': {'LR_FACTOR': 0.1,
  'LR_TRIGGER': [],
  'MIN_DELTA': 0.0,
  'PATIENCE': 10,
  'PATIENCE_LR': 2,
  'TENSORBOARD': {'SAVE_GRAPH': True, 'USE_TENSORBOARD': False}},
 'CALLBACKS': {'LR_FACTOR': 0.1, 'LR_TRIGGER': [10]},
 'DATAAUGMENTATION': {'DEFAULT_DICT': {'horizontal_flip': True}},
 'DATASET': {'NAME': 'pascalvoc',
  'PATH': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
  'SHUFFLE': True,
  'TEST': 'test',
  'TRAIN': 'trainval'},
 'DEBUG': {'IS_TEST': False},
 'EPSILON': 1e-07,
 'IMAGE': {'IMG_SIZE': 448, 'N_CHANNELS': 3},
 'MULTIP': {'MAX_QUEUE_SIZE': 10, 'N_WORKERS': 2, 'USE_MULTIPROCESS': False},
 'RANDOM_SEED': 1,
 'TRAINING': {'N_EPOCHS': 20, 'OPTIMIZER': 'sgd', 'START_LR': 0.01},
 'VERBOSE': True}

In [8]:
pprint(cfg)
new_cfg = cfg

{'ARCHI': {'CLASSIFIER': 'resnet50', 'LOSS': 'bce', 'NAME': 'baseline'},
 'BATCH_SIZE': 16,
 'CALLBACK': {'LR_FACTOR': 0.1,
              'LR_TRIGGER': [],
              'MIN_DELTA': 0.0,
              'PATIENCE': 10,
              'PATIENCE_LR': 2,
              'TENSORBOARD': {'SAVE_GRAPH': True, 'USE_TENSORBOARD': False}},
 'CALLBACKS': {'LR_FACTOR': 0.1, 'LR_TRIGGER': [10]},
 'DATAAUGMENTATION': {'DEFAULT_DICT': {'horizontal_flip': True}},
 'DATASET': {'NAME': 'pascalvoc',
             'PATH': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
             'SHUFFLE': True,
             'TEST': 'test',
             'TRAIN': 'trainval'},
 'DEBUG': {'IS_TEST': False},
 'EPSILON': 1e-07,
 'IMAGE': {'IMG_SIZE': 448, 'N_CHANNELS': 3},
 'MULTIP': {'MAX_QUEUE_SIZE': 10, 'N_WORKERS': 2, 'USE_MULTIPROCESS': False},
 'RANDOM_SEED': 1,
 'TRAINING': {'N_EPOCHS': 20, 'OPTIMIZER': 'sgd', 'START_LR': 0.01},
 'VERBOSE': True}


In [11]:
# save config
config_path = '/home/caleml/config_test.yaml'
with open(config_path, 'w+') as f_conf:
    yaml.dump(new_cfg, f_conf)

In [15]:
# load config
config_path = '/home/caleml/config_test.yaml'
with open(config_path, 'r') as f_in:
    loaded_conf = yaml.load(f_in)

In [16]:
pprint(loaded_conf)

{'ARCHI': {'CLASSIFIER': 'resnet50', 'LOSS': 'bce', 'NAME': 'baseline'},
 'BATCH_SIZE': 16,
 'CALLBACK': {'LR_FACTOR': 0.1,
              'LR_TRIGGER': [],
              'MIN_DELTA': 0.0,
              'PATIENCE': 10,
              'PATIENCE_LR': 2,
              'TENSORBOARD': {'SAVE_GRAPH': True, 'USE_TENSORBOARD': False}},
 'CALLBACKS': {'LR_FACTOR': 0.1, 'LR_TRIGGER': [10]},
 'DATAAUGMENTATION': {'DEFAULT_DICT': {'horizontal_flip': True}},
 'DATASET': {'NAME': 'pascalvoc',
             'PATH': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
             'SHUFFLE': True,
             'TEST': 'test',
             'TRAIN': 'trainval'},
 'DEBUG': {'IS_TEST': False},
 'EPSILON': 1e-07,
 'IMAGE': {'IMG_SIZE': 448, 'N_CHANNELS': 3},
 'MULTIP': {'MAX_QUEUE_SIZE': 10, 'N_WORKERS': 2, 'USE_MULTIPROCESS': False},
 'RANDOM_SEED': 1,
 'TRAINING': {'N_EPOCHS': 20, 'OPTIMIZER': 'sgd', 'START_LR': 0.01},
 'VERBOSE': True}


## Tests pascalVOC

In [20]:
prop = 100

In [21]:
data_dir = '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/'
dataset_train = PascalVOC(data_dir, 16, 'trainval', x_keys=['image'], y_keys=['multilabel'], p=prop)

In [24]:
exp_folder = '/home/caleml/partial_experiments/exp_20190903_1123_TESTNB'
os.makedirs(exp_folder, exist_ok=True)

In [27]:
model = Baseline(exp_folder, dataset_train.nb_classes, prop)
model.load_config('pv_relabel')
model.build()

Init input_shape (448, 448, 3)
Loading options

Loaded config

{'archi': {'classifier': 'resnet50', 'loss': 'bce', 'name': 'baseline'},
 'batch_size': 16,
 'dataset': {'name': 'pascalvoc',
             'path': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
             'test': 'test',
             'train': 'trainval'},
 'image': {'img_size': 448},
 'training': {'n_epochs': 20, 'optimizer': 'sgd', 'start_lr': 0.01}}



/home/caleml/.local/lib/python3.4/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


Outputs shape (None, 20)
Final model summary
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
image_input (InputLayer)     (None, 448, 448, 3)       0         
_________________________________________________________________
cls_model (Model)            (None, 14, 14, 2048)      23587712  
_________________________________________________________________
global_average_pooling2d (Gl (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 20)                40980     
Total params: 23,628,692
Trainable params: 23,575,572
Non-trainable params: 53,120
_________________________________________________________________


In [ ]:
# callbacks
from model.callbacks.relabeling_callback import RelabelCallback
cb_list = list()

map_cb = MAPCallback(X_test, Y_test, exp_folder, prop)
cb_list.append(map_cb)
cb_list.append(SaveModel(exp_folder, prop))

relabel_cb = RelabelCallback(dataset_train, exp_folder, 'kl', prop)
cb_list.append(relabel_cb)

In [32]:
a = 'animal'
'%s1' % a[0]

'a1'

In [2]:
min([1, 5])

1

In [5]:
a = np.array([0.54, 0.872497, 0.29374, 0.139864])

In [6]:
b = np.where(a > 0.5, 1, 0)

In [7]:
b

array([1, 1, 0, 0])

In [8]:
np.min(a)

0.139864

In [9]:
a.min()

0.139864

In [10]:
a = np.array([1, 2567, 3, 5093], dtype=np.int16)

In [11]:
b = np.array([4, 3, 2, 1], dtype=np.int16)

In [14]:
c = 255 * a / b
d = (a / b) * 255

In [15]:
c

array([  63.75,  170.  ,  382.5 , 1020.  ])

In [16]:
d

array([  63.75,  170.  ,  382.5 , 1020.  ])

In [17]:
a * c

array([  63.75,  340.  , 1147.5 , 4080.  ])

## test relabeling

In [3]:
y_true = np.zeros((8, 10))

In [4]:
y_true[:][:] = -1

# put some zeros and some ones
for line in y_true:
    ones = [np.random.randint(0, len(line) - 1) for i in range(np.random.randint(1, 3))]
    zeros = [np.random.randint(0, len(line) - 1) for i in range(5)]
    print(ones)
    line[ones] = 1
    line[zeros] = 0

[5]
[2]
[5]
[2]
[4]
[6]
[1]
[4]


In [5]:
y_true

array([[-1.,  0.,  0., -1., -1.,  0., -1., -1.,  0., -1.],
       [-1.,  0.,  1., -1., -1., -1.,  0.,  0.,  0., -1.],
       [-1., -1., -1., -1.,  0.,  0., -1., -1.,  0., -1.],
       [-1., -1.,  0., -1., -1., -1.,  0.,  0.,  0., -1.],
       [-1.,  0., -1., -1.,  1.,  0., -1.,  0.,  0., -1.],
       [ 0.,  0., -1.,  0., -1.,  0.,  0., -1., -1., -1.],
       [-1.,  0.,  0., -1., -1., -1., -1.,  0.,  0., -1.],
       [ 0., -1., -1.,  0.,  1., -1., -1.,  0.,  0., -1.]])

In [6]:
yk = np.random.rand(8, 10)
print(yk)

[[0.31758167 0.14547202 0.64511072 0.88200348 0.21635174 0.27855961
  0.21008615 0.0548783  0.32148914 0.31342073]
 [0.92449438 0.99196955 0.69292271 0.2872938  0.60950933 0.7971972
  0.95703965 0.6071477  0.61810452 0.70084569]
 [0.90460796 0.83244332 0.11012478 0.73372538 0.39853613 0.12078864
  0.41938148 0.9600263  0.35485419 0.51394682]
 [0.48379164 0.44634357 0.73381697 0.27509018 0.70589189 0.8080412
  0.20554191 0.04863043 0.35231251 0.27714793]
 [0.24620129 0.30776765 0.27779835 0.0243708  0.07517254 0.22291599
  0.21040443 0.29756407 0.75590584 0.00776722]
 [0.76087114 0.12037359 0.67115898 0.46749832 0.37853927 0.60114251
  0.11800136 0.85579306 0.5594698  0.38201092]
 [0.19309655 0.76361008 0.20260037 0.16802707 0.29846126 0.537478
  0.98199803 0.24327387 0.02717115 0.14053182]
 [0.92770257 0.51509554 0.89879271 0.13479303 0.87207998 0.21846154
  0.9032356  0.06389895 0.05867039 0.86087326]]


In [8]:
relevant_yk = np.where(y_true == 0, yk, 0)

In [9]:
relevant_yk

array([[0.        , 0.14547202, 0.64511072, 0.        , 0.        ,
        0.27855961, 0.        , 0.        , 0.32148914, 0.        ],
       [0.        , 0.99196955, 0.        , 0.        , 0.        ,
        0.        , 0.95703965, 0.6071477 , 0.61810452, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.39853613,
        0.12078864, 0.        , 0.        , 0.35485419, 0.        ],
       [0.        , 0.        , 0.73381697, 0.        , 0.        ,
        0.        , 0.20554191, 0.04863043, 0.35231251, 0.        ],
       [0.        , 0.30776765, 0.        , 0.        , 0.        ,
        0.22291599, 0.        , 0.29756407, 0.75590584, 0.        ],
       [0.76087114, 0.12037359, 0.        , 0.46749832, 0.        ,
        0.60114251, 0.11800136, 0.        , 0.        , 0.        ],
       [0.        , 0.76361008, 0.20260037, 0.        , 0.        ,
        0.        , 0.        , 0.24327387, 0.02717115, 0.        ],
       [0.92770257, 0.        , 0.       

In [10]:
sorted_indexes = np.argsort(relevant_yk, axis=None)
print(sorted_indexes)

relevant_yk.shape

[ 0 31 33 34 35 40 42 43 44 46 49 52 54 30 57 59 60 63 64 65 66 69 71 72
 74 75 76 58 29 39 27  3  4  6  7  9 10 12 13 14 19 20 15 79 22 23 26 21
 68 37 78 77 56 51 25 73  1 62 36 45 67  5 47 41  8 38 28 24 53 55 17 18
  2 32 48 50 61 70 16 11]


(8, 10)

In [19]:
values = [relevant_yk[i // 10][i % 10] for i in sorted_indexes]
print(values)
print(len(values))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.027171152580019453, 0.04863043492861163, 0.058670389841307125, 0.0638989533705493, 0.11800136283788387, 0.12037358564302503, 0.12078864226052322, 0.13479302541421156, 0.14547201769975215, 0.20260036939337, 0.2055419147072054, 0.22291598517914657, 0.24327386812783736, 0.27855960580252903, 0.29756407421498876, 0.3077676522946008, 0.3214891393064213, 0.3523125125140468, 0.3548541887752711, 0.3985361284880119, 0.4674983173652708, 0.6011425066466483, 0.6071477035548666, 0.6181045206532751, 0.6451107245200675, 0.7338169696327361, 0.7559058432655383, 0.7608711448112746, 0.7636100769455646, 0.9277025679178317, 0.9570396455369243, 0.9919695509054964]
80


In [15]:
# positive values
nb_positive_indexes = int((np.count_nonzero(values)) * (0.8 / 2))
positive_indexes = [(i // 10, i % 10) for i in sorted_indexes[len(values)-nb_positive_indexes: len(values)]]
print(positive_indexes)
print([yk[i] for i in positive_indexes])

[(5, 3), (5, 5), (1, 7), (1, 8), (0, 2), (3, 2), (4, 8), (5, 0), (6, 1), (7, 0), (1, 6), (1, 1)]
[0.4674983173652708, 0.6011425066466483, 0.6071477035548666, 0.6181045206532751, 0.6451107245200675, 0.7338169696327361, 0.7559058432655383, 0.7608711448112746, 0.7636100769455646, 0.9277025679178317, 0.9570396455369243, 0.9919695509054964]


In [18]:
# negative values
nb_zeros = len(values) - np.count_nonzero(values)
print(nb_zeros)
nb_negative_indexes = int((np.count_nonzero(values)) * (0.8 / 2))
negative_indexes = [(i // 10, i % 10) for i in sorted_indexes[nb_zeros: nb_zeros + nb_negative_indexes]]
print(negative_indexes)
print([yk[i] for i in negative_indexes])

48
[(6, 8), (3, 7), (7, 8), (7, 7), (5, 6), (5, 1), (2, 5), (7, 3), (0, 1), (6, 2), (3, 6), (4, 5)]
[0.027171152580019453, 0.04863043492861163, 0.058670389841307125, 0.0638989533705493, 0.11800136283788387, 0.12037358564302503, 0.12078864226052322, 0.13479302541421156, 0.14547201769975215, 0.20260036939337, 0.2055419147072054, 0.22291598517914657]


In [12]:
# all values
print(np.count_nonzero(values))
len(values)
nb_ok_indexes = int((np.count_nonzero(values)) * 0.33)
print(nb_ok_indexes)

32
10


In [96]:
final_indexes = [(i // 10, i % 10) for i in sorted_indexes[len(values)-nb_ok_indexes: len(values)]]
print(final_indexes)
print([b[i] for i in final_indexes])

[(2, 0), (7, 6), (3, 1), (1, 7), (6, 5), (0, 4), (6, 1), (7, 3), (3, 0), (3, 6)]
[0.8221002112729691, 0.8241341090018015, 0.8785830278280803, 0.8807645110382576, 0.9096892578646435, 0.930293222967397, 0.9594296220137665, 0.9603784752810169, 0.9717019435649444, 0.9773027884522567]


In [70]:
range(79 - 15, 79)

range(64, 79)

In [72]:
print([i for i in range(len(values)-nb_ok_indexes, len(values))])

[65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]


In [97]:
relabel = a.copy()

In [98]:
relabel

array([[ 0.,  1., -1.,  0.,  0., -1., -1., -1., -1., -1.],
       [ 0., -1., -1., -1.,  1., -1., -1.,  0.,  0., -1.],
       [ 0.,  0.,  0., -1.,  0.,  0., -1., -1.,  1., -1.],
       [ 0.,  0., -1.,  0., -1.,  1.,  0., -1., -1., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [-1.,  0., -1., -1.,  0.,  0.,  0.,  1., -1., -1.],
       [-1.,  0., -1.,  0.,  0., -1.,  0.,  0., -1., -1.]])

In [99]:
x = [elt[0] for elt in final_indexes]
y = [elt[1] for elt in final_indexes]
relabel[(x, y)] = 1

In [100]:
relabel

array([[ 0.,  1., -1.,  0.,  1., -1., -1., -1., -1., -1.],
       [ 0., -1., -1., -1.,  1., -1., -1.,  1.,  0., -1.],
       [ 1.,  0.,  0., -1.,  0.,  0., -1., -1.,  1., -1.],
       [ 1.,  1., -1.,  0., -1.,  1.,  1., -1., -1., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [-1.,  1., -1., -1.,  0.,  1.,  0.,  1., -1., -1.],
       [-1.,  0., -1.,  1.,  0., -1.,  1.,  0., -1., -1.]])

In [87]:
np.where(relabel == 0)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5,
        5, 6, 6, 6, 6, 7, 7, 7, 7, 7]),
 array([0, 3, 4, 0, 7, 8, 0, 1, 2, 4, 5, 0, 1, 3, 6, 0, 3, 7, 8, 0, 3, 7,
        8, 1, 4, 5, 6, 1, 3, 4, 6, 7]))

In [109]:
# sanity check
check = np.where(a != relabel, relabel, 0)
print(check)
assert np.count_nonzero(check) == nb_ok_indexes   # check we added the correct number of values
assert np.all(check[np.where(check != 0)] == 1)   # check we only added ones
assert np.all(a[np.where(check == 1)] == 0)       # check we added values only where the initial batch was 0

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]]


In [103]:
mmmh = np.where(check == 1)

In [104]:
mmmh

(array([0, 1, 2, 3, 3, 3, 6, 6, 7, 7]), array([4, 7, 0, 0, 1, 6, 1, 5, 3, 6]))

In [107]:
a[np.where(check == 1)] == 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## actual test with model

In [110]:
a = np.zeros(16)

In [111]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [112]:
a = [0, 1, 2, 3]
a = np.array(a)
a

array([0, 1, 2, 3])

In [113]:
a.shape

(4,)

In [114]:
(16,) + (224,224)

(16, 224, 224)

In [115]:
(16,) + (1,)

(16, 1)

In [116]:
(16,) + ()

(16,)

In [117]:
a.reshape(4, 1)

array([[0],
       [1],
       [2],
       [3]])

In [119]:
type(a[1])

numpy.int64

In [122]:
a = np.array([0, 1, 1, -1, 0, 1])
b = np.array([0, 1, 1, -1, 1, 1])

diff = np.where(a != b, b, -2)

In [123]:
diff

array([-2, -2, -2, -2,  1, -2])

In [125]:
assert np.all(diff[np.where(diff != -2)] == 1)
assert np.all(a[np.where(diff == 1)] == 0)

In [126]:
set([0, 1, 2]) - set([0, 1])

{2}

## strategy b

In [2]:
import numpy as np

In [12]:
logits = np.random.randint(-35, +35, (8, 10))

logits

array([[ 12,  21,  -6,   3,  27,   4, -16,   6,  16, -26],
       [-12, -22,  -3,   2,  19, -18, -34, -15, -24, -28],
       [ 28,   7,  25,  14,   4,   0,  10, -25, -34,  -1],
       [-24, -29,  23,   9,   8, -15,   4, -22,  -4,  20],
       [-21, -30,  10, -16,   9,  -6, -24,  14,  11,  13],
       [ 28,  26,  12,  21,  -7,  18, -26, -35, -25, -18],
       [ -1,  33,  -6, -22,  21,  19, -31,   1, -32,  14],
       [-10,  32,  24,  33, -19,  34, -31, -31,  14,  -7]])

In [6]:
y_true = np.zeros((8, 10))
y_true[:][:] = 0

# put some zeros and some ones
for line in y_true:
    ones = [np.random.randint(0, len(line) - 1) for i in range(np.random.randint(1, 3))]
    minus = [np.random.randint(0, len(line) - 1) for i in range(np.random.randint(1, 3))]
    line[ones] = 1
    line[minus] = -1
    
y_true

array([[-1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0., -1.,  0.,  0.,  1.,  0.],
       [ 1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.]])

In [14]:
# the goal is to take the 80% best absolute values
relevant_sk = np.where((y_true == 0), np.abs(logits), 0)
sorted_indexes = np.argsort(relevant_sk, axis=None)   # the indexes are flattened
sorted_values = [relevant_sk[i // 10][i % 10] for i in sorted_indexes]


In [15]:
print(relevant_sk)
print(sorted_indexes)
print(sorted_values)

[[ 0  0  6  3 27  4 16  6 16 26]
 [12 22  3  0 19 18  0 15 24 28]
 [ 0  0 25 14  4  0 10 25 34  1]
 [ 0 29 23  9  8  0  4  0  4 20]
 [21  0 10 16  0  0 24 14 11 13]
 [28 26  0 21  7  0 26 35  0 18]
 [ 0  0  6 22 21 19 31  1 32 14]
 [10 32  0  0  0 34 31 31 14  7]]
[ 0 30 37 41 25 44 45 21 20 52 55 58 60 16 35 61  1 72 74 73 13 29 67  3
 12 38 36 24  5  7  2 62 54 79 34 33 70 26 42 48 10 49 69 78 47 23 17  8
  6 43 59 15 65 14 39 53 40 64 11 63 32 18 46 27 22  9 51 56  4 19 50 31
 66 76 77 68 71 28 75 57]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 3, 3, 4, 4, 4, 4, 6, 6, 6, 7, 7, 8, 9, 10, 10, 10, 11, 12, 13, 14, 14, 14, 14, 15, 16, 16, 16, 18, 18, 19, 19, 20, 21, 21, 21, 22, 22, 23, 24, 24, 25, 25, 26, 26, 26, 27, 28, 28, 29, 31, 31, 31, 32, 32, 34, 34, 35]


In [17]:
relabel_batch = np.copy(y_true)

# take the best values and find corresponding indexes
nb_ok_indexes = int((np.count_nonzero(sorted_values)) * 0.80)
final_indexes = [(i // 10, i % 10) for i in sorted_indexes[len(sorted_values) - nb_ok_indexes: len(sorted_values)]]

# put the selected values as 1 in the relabel batch
xs = [elt[0] for elt in final_indexes]
ys = [elt[1] for elt in final_indexes]
relabel_batch[(xs, ys)] = np.sign(logits[(xs, ys)])

print(relabel_batch)

[[-1.  1.  0.  0.  1.  0. -1.  0.  1. -1.]
 [-1. -1.  0.  1.  1. -1. -1. -1. -1. -1.]
 [ 1. -1.  1.  1.  0.  0.  1. -1. -1.  0.]
 [-1. -1.  1.  1.  1.  1.  0.  1.  0.  1.]
 [-1.  1.  1. -1. -1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  0. -1. -1. -1.  1. -1.]
 [ 1. -1.  0. -1.  1.  1. -1.  0. -1.  1.]
 [-1.  1. -1.  1.  1.  1. -1. -1.  1. -1.]]
