In [23]:
import os
import yaml

In [4]:
import numpy as np

In [2]:
from pprint import pprint

In [3]:
from config.config_utils import dict_recursive_update
from config.config import cfg

from easydict import EasyDict as edict

In [18]:
from data.pascalvoc.pascalvoc import PascalVOC

Using TensorFlow backend.


In [26]:
from model.networks.baseline import Baseline

In [31]:
from model.callbacks.metric_callbacks import MAPCallback
from model.callbacks.save_callback import SaveModel
from model.callbacks.scheduler import lr_scheduler
from model.callbacks.relabeling_callback import RelabelCallback

## debug config

In [4]:
config_path = '/home/caleml/partial-labels/config/pv_baseline50_sgd_448lrs.yaml'
with open(config_path, 'r') as f_in:
    options = yaml.safe_load(f_in)

In [5]:
options

{'archi': {'classifier': 'resnet50', 'loss': 'bce', 'name': 'baseline'},
 'batch_size': 16,
 'callbacks': {'lr_factor': 0.1, 'lr_trigger': [10]},
 'dataset': {'name': 'pascalvoc',
  'path': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
  'test': 'test',
  'train': 'trainval'},
 'image': {'img_size': 448},
 'training': {'n_epochs': 20, 'optimizer': 'sgd', 'start_lr': 0.01}}

In [6]:
pprint(cfg)
old_cfg = cfg

{'BATCH_SIZE': 32,
 'CALLBACK': {'LR_FACTOR': 0.1,
              'LR_TRIGGER': [],
              'MIN_DELTA': 0.0,
              'PATIENCE': 10,
              'PATIENCE_LR': 2,
              'TENSORBOARD': {'SAVE_GRAPH': True, 'USE_TENSORBOARD': False}},
 'DATAAUGMENTATION': {'DEFAULT_DICT': {'horizontal_flip': True}},
 'DATASET': {'SHUFFLE': True},
 'DEBUG': {'IS_TEST': False},
 'EPSILON': 1e-07,
 'IMAGE': {'IMG_SIZE': 448, 'N_CHANNELS': 3},
 'MULTIP': {'MAX_QUEUE_SIZE': 10, 'N_WORKERS': 2, 'USE_MULTIPROCESS': False},
 'RANDOM_SEED': 1,
 'TRAINING': {'OPTIMIZER': 'adam', 'START_LR': 0.0001},
 'VERBOSE': True}


In [7]:
new_config = edict(options)
dict_recursive_update(cfg, new_config)

{'ARCHI': {'CLASSIFIER': 'resnet50', 'LOSS': 'bce', 'NAME': 'baseline'},
 'BATCH_SIZE': 16,
 'CALLBACK': {'LR_FACTOR': 0.1,
  'LR_TRIGGER': [],
  'MIN_DELTA': 0.0,
  'PATIENCE': 10,
  'PATIENCE_LR': 2,
  'TENSORBOARD': {'SAVE_GRAPH': True, 'USE_TENSORBOARD': False}},
 'CALLBACKS': {'LR_FACTOR': 0.1, 'LR_TRIGGER': [10]},
 'DATAAUGMENTATION': {'DEFAULT_DICT': {'horizontal_flip': True}},
 'DATASET': {'NAME': 'pascalvoc',
  'PATH': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
  'SHUFFLE': True,
  'TEST': 'test',
  'TRAIN': 'trainval'},
 'DEBUG': {'IS_TEST': False},
 'EPSILON': 1e-07,
 'IMAGE': {'IMG_SIZE': 448, 'N_CHANNELS': 3},
 'MULTIP': {'MAX_QUEUE_SIZE': 10, 'N_WORKERS': 2, 'USE_MULTIPROCESS': False},
 'RANDOM_SEED': 1,
 'TRAINING': {'N_EPOCHS': 20, 'OPTIMIZER': 'sgd', 'START_LR': 0.01},
 'VERBOSE': True}

In [8]:
pprint(cfg)
new_cfg = cfg

{'ARCHI': {'CLASSIFIER': 'resnet50', 'LOSS': 'bce', 'NAME': 'baseline'},
 'BATCH_SIZE': 16,
 'CALLBACK': {'LR_FACTOR': 0.1,
              'LR_TRIGGER': [],
              'MIN_DELTA': 0.0,
              'PATIENCE': 10,
              'PATIENCE_LR': 2,
              'TENSORBOARD': {'SAVE_GRAPH': True, 'USE_TENSORBOARD': False}},
 'CALLBACKS': {'LR_FACTOR': 0.1, 'LR_TRIGGER': [10]},
 'DATAAUGMENTATION': {'DEFAULT_DICT': {'horizontal_flip': True}},
 'DATASET': {'NAME': 'pascalvoc',
             'PATH': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
             'SHUFFLE': True,
             'TEST': 'test',
             'TRAIN': 'trainval'},
 'DEBUG': {'IS_TEST': False},
 'EPSILON': 1e-07,
 'IMAGE': {'IMG_SIZE': 448, 'N_CHANNELS': 3},
 'MULTIP': {'MAX_QUEUE_SIZE': 10, 'N_WORKERS': 2, 'USE_MULTIPROCESS': False},
 'RANDOM_SEED': 1,
 'TRAINING': {'N_EPOCHS': 20, 'OPTIMIZER': 'sgd', 'START_LR': 0.01},
 'VERBOSE': True}


In [11]:
# save config
config_path = '/home/caleml/config_test.yaml'
with open(config_path, 'w+') as f_conf:
    yaml.dump(new_cfg, f_conf)

In [15]:
# load config
config_path = '/home/caleml/config_test.yaml'
with open(config_path, 'r') as f_in:
    loaded_conf = yaml.load(f_in)

In [16]:
pprint(loaded_conf)

{'ARCHI': {'CLASSIFIER': 'resnet50', 'LOSS': 'bce', 'NAME': 'baseline'},
 'BATCH_SIZE': 16,
 'CALLBACK': {'LR_FACTOR': 0.1,
              'LR_TRIGGER': [],
              'MIN_DELTA': 0.0,
              'PATIENCE': 10,
              'PATIENCE_LR': 2,
              'TENSORBOARD': {'SAVE_GRAPH': True, 'USE_TENSORBOARD': False}},
 'CALLBACKS': {'LR_FACTOR': 0.1, 'LR_TRIGGER': [10]},
 'DATAAUGMENTATION': {'DEFAULT_DICT': {'horizontal_flip': True}},
 'DATASET': {'NAME': 'pascalvoc',
             'PATH': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
             'SHUFFLE': True,
             'TEST': 'test',
             'TRAIN': 'trainval'},
 'DEBUG': {'IS_TEST': False},
 'EPSILON': 1e-07,
 'IMAGE': {'IMG_SIZE': 448, 'N_CHANNELS': 3},
 'MULTIP': {'MAX_QUEUE_SIZE': 10, 'N_WORKERS': 2, 'USE_MULTIPROCESS': False},
 'RANDOM_SEED': 1,
 'TRAINING': {'N_EPOCHS': 20, 'OPTIMIZER': 'sgd', 'START_LR': 0.01},
 'VERBOSE': True}


## Tests pascalVOC

In [20]:
prop = 100

In [21]:
data_dir = '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/'
dataset_train = PascalVOC(data_dir, 16, 'trainval', x_keys=['image'], y_keys=['multilabel'], p=prop)

In [24]:
exp_folder = '/home/caleml/partial_experiments/exp_20190903_1123_TESTNB'
os.makedirs(exp_folder, exist_ok=True)

In [27]:
model = Baseline(exp_folder, dataset_train.nb_classes, prop)
model.load_config('pv_relabel')
model.build()

Init input_shape (448, 448, 3)
Loading options

Loaded config

{'archi': {'classifier': 'resnet50', 'loss': 'bce', 'name': 'baseline'},
 'batch_size': 16,
 'dataset': {'name': 'pascalvoc',
             'path': '/home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/',
             'test': 'test',
             'train': 'trainval'},
 'image': {'img_size': 448},
 'training': {'n_epochs': 20, 'optimizer': 'sgd', 'start_lr': 0.01}}



/home/caleml/.local/lib/python3.4/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


Outputs shape (None, 20)
Final model summary
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
image_input (InputLayer)     (None, 448, 448, 3)       0         
_________________________________________________________________
cls_model (Model)            (None, 14, 14, 2048)      23587712  
_________________________________________________________________
global_average_pooling2d (Gl (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 20)                40980     
Total params: 23,628,692
Trainable params: 23,575,572
Non-trainable params: 53,120
_________________________________________________________________


In [ ]:
# callbacks
from model.callbacks.relabeling_callback import RelabelCallback
cb_list = list()

map_cb = MAPCallback(X_test, Y_test, exp_folder, prop)
cb_list.append(map_cb)
cb_list.append(SaveModel(exp_folder, prop))

relabel_cb = RelabelCallback(dataset_train, exp_folder, 'kl', prop)
cb_list.append(relabel_cb)

In [32]:
a = 'animal'
'%s1' % a[0]

'a1'

In [2]:
min([1, 5])

1

In [5]:
a = np.array([0.54, 0.872497, 0.29374, 0.139864])

In [6]:
b = np.where(a > 0.5, 1, 0)

In [7]:
b

array([1, 1, 0, 0])

In [8]:
np.min(a)

0.139864

In [9]:
a.min()

0.139864

In [10]:
a = np.array([1, 2567, 3, 5093], dtype=np.int16)

In [11]:
b = np.array([4, 3, 2, 1], dtype=np.int16)

In [14]:
c = 255 * a / b
d = (a / b) * 255

In [15]:
c

array([  63.75,  170.  ,  382.5 , 1020.  ])

In [16]:
d

array([  63.75,  170.  ,  382.5 , 1020.  ])

In [17]:
a * c

array([  63.75,  340.  , 1147.5 , 4080.  ])

## test relabeling

In [20]:
a = np.zeros((8, 10))

In [44]:
a[:][:] = -1

# put some zeros and some ones
for line in a:
    ones = [np.random.randint(0, len(line) - 1) for i in range(np.random.randint(1, 3))]
    zeros = [np.random.randint(0, len(line) - 1) for i in range(5)]
    print(ones)
    line[ones] = 1
    line[zeros] = 0

[1, 0]
[4]
[8, 8]
[5]
[0]
[0]
[4, 7]
[3]


In [46]:
a

array([[ 0.,  1., -1.,  0.,  0., -1., -1., -1., -1., -1.],
       [ 0., -1., -1., -1.,  1., -1., -1.,  0.,  0., -1.],
       [ 0.,  0.,  0., -1.,  0.,  0., -1., -1.,  1., -1.],
       [ 0.,  0., -1.,  0., -1.,  1.,  0., -1., -1., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [-1.,  0., -1., -1.,  0.,  0.,  0.,  1., -1., -1.],
       [-1.,  0., -1.,  0.,  0., -1.,  0.,  0., -1., -1.]])

In [50]:
yk = np.random.rand(8, 10)
print(yk)

[[0.7892151  0.48961266 0.58825933 0.37622917 0.93029322 0.72791149
  0.23463466 0.72381892 0.70641471 0.61003805]
 [0.70565933 0.07210103 0.80044418 0.12235055 0.3463545  0.72456613
  0.7425328  0.88076451 0.31872521 0.30621604]
 [0.82210021 0.46269845 0.13738335 0.98828442 0.36587978 0.24957262
  0.52975795 0.18345812 0.3923937  0.35011697]
 [0.97170194 0.87858303 0.93677425 0.29893387 0.57283222 0.85416751
  0.97730279 0.09268791 0.85836214 0.35292269]
 [0.20776014 0.30116243 0.68923473 0.11669586 0.88748813 0.56536253
  0.04472967 0.64969951 0.45696584 0.26187452]
 [0.63519103 0.54609243 0.12034008 0.50949203 0.66798039 0.51734761
  0.50546281 0.37216029 0.54121498 0.29086926]
 [0.37358954 0.95942962 0.66961    0.90893919 0.55785545 0.90968926
  0.30081559 0.53835932 0.37989015 0.87820026]
 [0.07438424 0.57264806 0.26711109 0.96037848 0.0173247  0.04219673
  0.82413411 0.55139042 0.81407396 0.32260926]]


In [92]:
b = np.where(a == 0, yk, 0)

In [52]:
b

array([[0.        , 0.48961266, 0.58825933, 0.        , 0.        ,
        0.72791149, 0.23463466, 0.72381892, 0.70641471, 0.61003805],
       [0.        , 0.07210103, 0.80044418, 0.12235055, 0.3463545 ,
        0.72456613, 0.7425328 , 0.        , 0.        , 0.30621604],
       [0.        , 0.        , 0.        , 0.98828442, 0.        ,
        0.        , 0.52975795, 0.18345812, 0.3923937 , 0.35011697],
       [0.        , 0.        , 0.93677425, 0.        , 0.57283222,
        0.85416751, 0.        , 0.09268791, 0.85836214, 0.35292269],
       [0.        , 0.30116243, 0.68923473, 0.        , 0.88748813,
        0.56536253, 0.04472967, 0.        , 0.        , 0.26187452],
       [0.        , 0.54609243, 0.12034008, 0.        , 0.66798039,
        0.51734761, 0.50546281, 0.        , 0.        , 0.29086926],
       [0.37358954, 0.        , 0.66961   , 0.90893919, 0.        ,
        0.        , 0.        , 0.53835932, 0.37989015, 0.87820026],
       [0.07438424, 0.        , 0.2671110

In [93]:
sorted_indexes = np.argsort(b, axis=None)
print(sorted_indexes)

b.shape

[39 34 35 37 38 78 41 42 44 45 46 49 51 32 52 55 56 59 60 62 63 67 68 69
 70 72 75 54 29 79 13  7  8  9 11 12 28 14 15  6  2 19 16  5 27 26  1 23
 74 43 22 40 25 33 66 18 24 57  3 48 21 53 58 77 64 71 50 47 10  0 20 76
 31 17 65  4 61 73 30 36]


(8, 10)

In [94]:
values = [b[i // 10][i % 10] for i in sorted_indexes]
print(values)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01732470047018353, 0.11669585731948906, 0.1373833549235326, 0.20776014383947106, 0.2495726197245669, 0.29893386855808124, 0.30081558705634115, 0.3187252110308946, 0.3658797775750193, 0.3721602913296108, 0.3762291655356973, 0.4569658441699257, 0.4626984539632323, 0.5094920307920717, 0.5412149783795069, 0.5513904197676635, 0.5578554519016428, 0.5726480584709357, 0.6351910256778213, 0.6496995095508425, 0.7056593300859733, 0.7892150990424038, 0.8221002112729691, 0.8241341090018015, 0.8785830278280803, 0.8807645110382576, 0.9096892578646435, 0.930293222967397, 0.9594296220137665, 0.9603784752810169, 0.9717019435649444, 0.9773027884522567]


In [60]:
64 // 10

6

In [95]:
print(np.count_nonzero(values))
len(values)
nb_ok_indexes = int((np.count_nonzero(values)) * 0.33)
print(nb_ok_indexes)

32
10


In [96]:
final_indexes = [(i // 10, i % 10) for i in sorted_indexes[len(values)-nb_ok_indexes: len(values)]]
print(final_indexes)
print([b[i] for i in final_indexes])

[(2, 0), (7, 6), (3, 1), (1, 7), (6, 5), (0, 4), (6, 1), (7, 3), (3, 0), (3, 6)]
[0.8221002112729691, 0.8241341090018015, 0.8785830278280803, 0.8807645110382576, 0.9096892578646435, 0.930293222967397, 0.9594296220137665, 0.9603784752810169, 0.9717019435649444, 0.9773027884522567]


In [70]:
range(79 - 15, 79)

range(64, 79)

In [72]:
print([i for i in range(len(values)-nb_ok_indexes, len(values))])

[65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]


In [97]:
relabel = a.copy()

In [98]:
relabel

array([[ 0.,  1., -1.,  0.,  0., -1., -1., -1., -1., -1.],
       [ 0., -1., -1., -1.,  1., -1., -1.,  0.,  0., -1.],
       [ 0.,  0.,  0., -1.,  0.,  0., -1., -1.,  1., -1.],
       [ 0.,  0., -1.,  0., -1.,  1.,  0., -1., -1., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [-1.,  0., -1., -1.,  0.,  0.,  0.,  1., -1., -1.],
       [-1.,  0., -1.,  0.,  0., -1.,  0.,  0., -1., -1.]])

In [99]:
x = [elt[0] for elt in final_indexes]
y = [elt[1] for elt in final_indexes]
relabel[(x, y)] = 1

In [100]:
relabel

array([[ 0.,  1., -1.,  0.,  1., -1., -1., -1., -1., -1.],
       [ 0., -1., -1., -1.,  1., -1., -1.,  1.,  0., -1.],
       [ 1.,  0.,  0., -1.,  0.,  0., -1., -1.,  1., -1.],
       [ 1.,  1., -1.,  0., -1.,  1.,  1., -1., -1., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [ 0., -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.],
       [-1.,  1., -1., -1.,  0.,  1.,  0.,  1., -1., -1.],
       [-1.,  0., -1.,  1.,  0., -1.,  1.,  0., -1., -1.]])

In [87]:
np.where(relabel == 0)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5,
        5, 6, 6, 6, 6, 7, 7, 7, 7, 7]),
 array([0, 3, 4, 0, 7, 8, 0, 1, 2, 4, 5, 0, 1, 3, 6, 0, 3, 7, 8, 0, 3, 7,
        8, 1, 4, 5, 6, 1, 3, 4, 6, 7]))

In [109]:
# sanity check
check = np.where(a != relabel, relabel, 0)
print(check)
assert np.count_nonzero(check) == nb_ok_indexes   # check we added the correct number of values
assert np.all(check[np.where(check != 0)] == 1)   # check we only added ones
assert np.all(a[np.where(check == 1)] == 0)       # check we added values only where the initial batch was 0

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]]


In [103]:
mmmh = np.where(check == 1)

In [104]:
mmmh

(array([0, 1, 2, 3, 3, 3, 6, 6, 7, 7]), array([4, 7, 0, 0, 1, 6, 1, 5, 3, 6]))

In [107]:
a[np.where(check == 1)] == 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## actual test with model

In [110]:
a = np.zeros(16)

In [111]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [112]:
a = [0, 1, 2, 3]
a = np.array(a)
a

array([0, 1, 2, 3])

In [113]:
a.shape

(4,)

In [114]:
(16,) + (224,224)

(16, 224, 224)

In [115]:
(16,) + (1,)

(16, 1)

In [116]:
(16,) + ()

(16,)

In [117]:
a.reshape(4, 1)

array([[0],
       [1],
       [2],
       [3]])

In [119]:
type(a[1])

numpy.int64

In [122]:
a = np.array([0, 1, 1, -1, 0, 1])
b = np.array([0, 1, 1, -1, 1, 1])

diff = np.where(a != b, b, -2)

In [123]:
diff

array([-2, -2, -2, -2,  1, -2])

In [125]:
assert np.all(diff[np.where(diff != -2)] == 1)
assert np.all(a[np.where(diff == 1)] == 0)

In [126]:
set([0, 1, 2]) - set([0, 1])

{2}